import type { Video, Category, User, Collection } from '../types'

export const mockCategories: Category[] = [
  { id: '1', name: 'Education', slug: 'education', description: 'Educational content', created_at: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'Science', slug: 'science', description: 'Science videos', created_at: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Technology', slug: 'technology', description: 'Tech tutorials', created_at: '2024-01-01T00:00:00Z' },
  { id: '4', name: 'Islamic', slug: 'islamic', description: 'Islamic content', created_at: '2024-01-01T00:00:00Z' },
  { id: '5', name: 'Mathematics', slug: 'mathematics', description: 'Math lessons', created_at: '2024-01-01T00:00:00Z' },
  { id: '6', name: 'English', slug: 'english', description: 'English lessons', created_at: '2024-01-01T00:00:00Z' },
  { id: '7', name: 'Tutorials', slug: 'tutorials', description: 'How-to guides', created_at: '2024-01-01T00:00:00Z' },
  { id: '8', name: 'Announcements', slug: 'announcements', description: 'Important updates', created_at: '2024-01-01T00:00:00Z' },
]

export const mockVideos: Video[] = [
  {
    id: '1',
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtube_video_id: 'dQw4w9WgXcQ',
    title: 'Physics Chapter 1: Motion and Force',
    description: 'An introduction to the fundamental concepts of motion and force in classical mechanics. This video covers Newton\'s three laws of motion with real-world examples.',
    thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    category_id: '2',
    category: { id: '2', name: 'Science', slug: 'science', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: true,
    views: 4829,
    tags: ['physics', 'motion', 'force', 'science'],
    duration: '12:34',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    youtube_url: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    youtube_video_id: '9bZkp7q19f0',
    title: 'Biology Chapter 2: Cell Division',
    description: 'Understanding mitosis and meiosis — the two types of cell division. Includes diagrams and animations to help visualize the process.',
    thumbnail_url: 'https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg',
    category_id: '2',
    category: { id: '2', name: 'Science', slug: 'science', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: false,
    views: 3821,
    tags: ['biology', 'cells', 'mitosis', 'science'],
    duration: '18:45',
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    youtube_url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    youtube_video_id: 'jNQXAC9IVRw',
    title: 'English Grammar: Tenses Explained',
    description: 'A comprehensive guide to all 12 English tenses with examples, practice exercises, and common mistakes to avoid.',
    thumbnail_url: 'https://img.youtube.com/vi/jNQXAC9IVRw/hqdefault.jpg',
    category_id: '6',
    category: { id: '6', name: 'English', slug: 'english', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: false,
    views: 2941,
    tags: ['english', 'grammar', 'tenses'],
    duration: '22:10',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '4',
    youtube_url: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
    youtube_video_id: 'M7lc1UVf-VE',
    title: 'Mathematics: Quadratic Equations',
    description: 'Step-by-step guide to solving quadratic equations using factoring, completing the square, and the quadratic formula.',
    thumbnail_url: 'https://img.youtube.com/vi/M7lc1UVf-VE/hqdefault.jpg',
    category_id: '5',
    category: { id: '5', name: 'Mathematics', slug: 'mathematics', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: true,
    views: 1540,
    tags: ['math', 'algebra', 'quadratic'],
    duration: '15:22',
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
  },
  {
    id: '5',
    youtube_url: 'https://www.youtube.com/watch?v=eVTXPUF4Oz4',
    youtube_video_id: 'eVTXPUF4Oz4',
    title: 'React Tutorial for Beginners',
    description: 'Complete React JS tutorial covering components, state, props, hooks, and modern React patterns.',
    thumbnail_url: 'https://img.youtube.com/vi/eVTXPUF4Oz4/hqdefault.jpg',
    category_id: '3',
    category: { id: '3', name: 'Technology', slug: 'technology', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: false,
    views: 980,
    tags: ['react', 'javascript', 'web development', 'tutorial'],
    duration: '45:00',
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
  {
    id: '6',
    youtube_url: 'https://www.youtube.com/watch?v=ZZ5LBwRSXyE',
    youtube_video_id: 'ZZ5LBwRSXyE',
    title: 'Biology: Monohybrid Cross',
    description: 'Detailed explanation of Mendelian genetics and monohybrid crosses with Punnett square practice.',
    thumbnail_url: 'https://img.youtube.com/vi/ZZ5LBwRSXyE/hqdefault.jpg',
    category_id: '2',
    category: { id: '2', name: 'Science', slug: 'science', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: false,
    views: 756,
    tags: ['biology', 'genetics', 'mendel'],
    duration: '9:15',
    created_at: '2024-02-18T00:00:00Z',
    updated_at: '2024-02-18T00:00:00Z',
  },
  {
    id: '7',
    youtube_url: 'https://www.youtube.com/watch?v=aircAruvnKk',
    youtube_video_id: 'aircAruvnKk',
    title: 'Neural Networks Explained',
    description: 'Visual introduction to how neural networks and deep learning work, from perceptrons to modern architectures.',
    thumbnail_url: 'https://img.youtube.com/vi/aircAruvnKk/hqdefault.jpg',
    category_id: '3',
    category: { id: '3', name: 'Technology', slug: 'technology', created_at: '2024-01-01T00:00:00Z' },
    status: 'draft',
    is_featured: false,
    views: 0,
    tags: ['AI', 'machine learning', 'neural networks'],
    duration: '19:13',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '8',
    youtube_url: 'https://www.youtube.com/watch?v=HluANRwPyNo',
    youtube_video_id: 'HluANRwPyNo',
    title: 'Islamic Studies: Five Pillars of Islam',
    description: 'An educational overview of the five pillars of Islam — Shahada, Salah, Zakat, Sawm, and Hajj.',
    thumbnail_url: 'https://img.youtube.com/vi/HluANRwPyNo/hqdefault.jpg',
    category_id: '4',
    category: { id: '4', name: 'Islamic', slug: 'islamic', created_at: '2024-01-01T00:00:00Z' },
    status: 'published',
    is_featured: false,
    views: 1230,
    tags: ['islam', 'religion', 'five pillars'],
    duration: '14:50',
    created_at: '2024-03-05T00:00:00Z',
    updated_at: '2024-03-05T00:00:00Z',
  },
]

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@videohub.com',
    role: 'admin',
    created_at: '2024-01-01T00:00:00Z',
  },
]

export const mockCollections: Collection[] = [
  {
    id: '1',
    title: 'Class 10 Physics',
    description: 'Complete physics curriculum for Class 10 students',
    created_at: '2024-01-01T00:00:00Z',
    videos: mockVideos.filter(v => v.tags?.includes('physics')),
  },
  {
    id: '2',
    title: 'Biology Fundamentals',
    description: 'Core biology concepts from cells to genetics',
    created_at: '2024-01-15T00:00:00Z',
    videos: mockVideos.filter(v => v.tags?.includes('biology')),
  },
]
